# Generated by Django 5.2.1 on 2025-07-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_newslettersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
