# Generated by Django 5.2.1 on 2025-07-11 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='visits',
            new_name='visit_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=0.0003142536475869809, max_length=500),
            preserve_default=False,
        ),
    ]
